[package]
name = "rust_bepuphysics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
profile = []

[dependencies]
glam = { version = "0.32" }
num-traits = "0.2"
